### ISSUE TITLE
Tamper Proof ID

### ISSUE THREAD

**Issue by dharmocracy** [MrChrisJ/World-Citizenship#10]
Before issuing the ID for anybody.. can we do a test to ensure they are hack proof and not open to forgery. I have a few lads who can help on that front. (the forgery side not the hacking)

**Comment by jacquesrudolph** [comment]
A New Form of ID Allows You to Be a Citizen of the World 

Instructions on how to create a BlockchainID

Video here:
http://youtu.be/1iAg6BITPdc

Github project:
https://github.com/MrChrisJ/World-Citizenship

I seriously advise the OCU-Organisation pour une Citoyenneté Universelle get on board with this project.

Join the
O U C - Organization for Universal Citizenship

Join us on facebook
http://www.facebook.com/worldcitizenfriends

Call to Action by:
http://www.facebook.com/citoyenneteuniverselle

Published by: 
http://www.o-c-u.org/en/

**Comment by jacquesrudolph** [comment]
![10365899_245335692335031_7697973720311418962_n](https://cloud.githubusercontent.com/assets/10696773/5892154/492699d4-a46a-11e4-83fa-ae3230f48332.jpg)

**Comment by jacquesrudolph** [comment]
![1610110_242666469268620_8582873160744484891_n](https://cloud.githubusercontent.com/assets/10696773/5892191/2ade9fde-a46b-11e4-9f5b-df16d39c2561.jpg)
